import type { Schema } from '../../src/types';

export const schema: Schema = {
  basePath: '/api/v1',
  enums: [
    {
      deprecated: false,
      description: null,
      example: null,
      name: 'invoice_status',
      scope: null,
      values: ['draft', 'sent', 'paid'],
    },
  ],
  errorCodes: [],
  fingerprint: '0123456789abcdef',
  info: null,
  locales: ['en'],
  resources: [
    {
      actions: [
        {
          deprecated: false,
          description: null,
          method: 'get',
          name: 'invoices.index',
          operationId: null,
          path: '/invoices',
          raises: [],
          request: {
            body: [],
            description: null,
            query: [],
          },
          response: {
            body: {
              deprecated: false,
              description: null,
              example: null,
              max: null,
              min: null,
              name: '',
              nullable: false,
              of: {
                deprecated: false,
                description: null,
                name: '',
                nullable: false,
                optional: false,
                reference: 'invoice',
                type: 'reference',
              },
              optional: false,
              type: 'array',
            },
            description: null,
            noContent: false,
          },
          summary: null,
          tags: [],
        },
        {
          deprecated: false,
          description: null,
          method: 'get',
          name: 'invoices.show',
          operationId: null,
          path: '/invoices/:id',
          raises: [],
          request: {
            body: [],
            description: null,
            query: [],
          },
          response: {
            body: {
              deprecated: false,
              description: null,
              name: '',
              nullable: false,
              optional: false,
              reference: 'invoice',
              type: 'reference',
            },
            description: null,
            noContent: false,
          },
          summary: null,
          tags: [],
        },
      ],
      identifier: 'invoices',
      name: 'invoices',
      parentIdentifiers: [],
      path: '/invoices',
      resources: [],
      scope: null,
    },
  ],
  types: [
    {
      deprecated: false,
      description: null,
      example: null,
      extends: [],
      name: 'invoice',
      recursive: false,
      scope: null,
      shape: [
        {
          default: undefined,
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'id',
          nullable: false,
          optional: false,
          type: 'uuid',
        },
        {
          default: undefined,
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'number',
          nullable: false,
          optional: false,
          type: 'string',
        },
        {
          default: undefined,
          deprecated: false,
          description: null,
          enum: 'invoice_status',
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'status',
          nullable: false,
          optional: false,
          type: 'string',
        },
      ],
      type: 'object',
    },
  ],
};
/**
 * A schema whose sole object type exercises every `Param` variant and
 * modifier combination. Used to assert that both generators emit the
 * expected output for each branch of their mappers via the public
 * `generate()` API.
 */
export const primitivesSchema: Schema = {
  basePath: '/api/v1',
  enums: [
    {
      deprecated: false,
      description: null,
      example: null,
      name: 'color',
      scope: null,
      values: ['red', 'green', 'blue'],
    },
  ],
  errorCodes: [],
  fingerprint: '0123456789abcdef',
  info: null,
  locales: ['en'],
  resources: [],
  types: [
    {
      deprecated: false,
      description: null,
      example: null,
      extends: [],
      name: 'primitives',
      recursive: false,
      scope: null,
      shape: [
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'str',
          nullable: false,
          optional: false,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'int',
          nullable: false,
          optional: false,
          type: 'integer',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          max: null,
          min: null,
          name: 'num',
          nullable: false,
          optional: false,
          type: 'number',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          max: null,
          min: null,
          name: 'dec',
          nullable: false,
          optional: false,
          type: 'decimal',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'bool',
          nullable: false,
          optional: false,
          type: 'boolean',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'd',
          nullable: false,
          optional: false,
          type: 'date',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'dt',
          nullable: false,
          optional: false,
          type: 'datetime',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 't',
          nullable: false,
          optional: false,
          type: 'time',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'id',
          nullable: false,
          optional: false,
          type: 'uuid',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          name: 'bin',
          nullable: false,
          optional: false,
          type: 'binary',
        },
        {
          deprecated: false,
          description: null,
          name: 'lit',
          nullable: false,
          optional: false,
          type: 'literal',
          value: 'fixed',
        },
        {
          deprecated: false,
          description: null,
          example: null,
          max: null,
          min: null,
          name: 'strs',
          nullable: false,
          of: {
            deprecated: false,
            description: null,
            enum: undefined,
            example: null,
            format: null,
            max: null,
            min: null,
            name: '',
            nullable: false,
            optional: false,
            type: 'string',
          },
          optional: false,
          type: 'array',
        },
        {
          deprecated: false,
          description: null,
          example: null,
          name: 'nums',
          nullable: false,
          of: {
            deprecated: false,
            description: null,
            enum: undefined,
            example: null,
            max: null,
            min: null,
            name: '',
            nullable: false,
            optional: false,
            type: 'number',
          },
          optional: false,
          type: 'record',
        },
        {
          deprecated: false,
          description: null,
          discriminator: null,
          name: 'either',
          nullable: false,
          optional: false,
          type: 'union',
          variants: [
            {
              deprecated: false,
              description: null,
              enum: undefined,
              example: null,
              format: null,
              max: null,
              min: null,
              name: '',
              nullable: false,
              optional: false,
              type: 'string',
            },
            {
              deprecated: false,
              description: null,
              enum: undefined,
              example: null,
              format: null,
              max: null,
              min: null,
              name: '',
              nullable: false,
              optional: false,
              type: 'integer',
            },
          ],
        },
        {
          deprecated: false,
          description: null,
          name: 'any',
          nullable: false,
          optional: false,
          type: 'unknown',
        },
        {
          deprecated: false,
          description: null,
          enum: 'color',
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'shade',
          nullable: false,
          optional: false,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: 10,
          min: 1,
          name: 'bounded',
          nullable: false,
          optional: false,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: 'email',
          max: null,
          min: null,
          name: 'email',
          nullable: false,
          optional: false,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'nullableStr',
          nullable: true,
          optional: false,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'optionalStr',
          nullable: false,
          optional: true,
          type: 'string',
        },
        {
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'nullableOptionalStr',
          nullable: true,
          optional: true,
          type: 'string',
        },
        {
          default: 'hello',
          deprecated: false,
          description: null,
          enum: undefined,
          example: null,
          format: null,
          max: null,
          min: null,
          name: 'defaultedStr',
          nullable: false,
          optional: false,
          type: 'string',
        },
      ],
      type: 'object',
    },
  ],
};
